services:
  latest:
    image: cl4n/duplicity:latest
    build:
      context: latest
    volumes:
      - ./latest:/mnt
    command: ['duplicity', '--version']
  stable:
    image: cl4n/duplicity:stable
    build:
      context: stable
    command: ['duplicity', '--version']
